### ISSUE TITLE
worldStateManager: check that the same ID is not used twice

### ISSUE THREAD

**Issue by gsaponaro** [robotology/poeticon#24]
Related to #22 

If OPC already contains id_50 and I ask the activeParticleTrack to ```countFrom 50```, worldStateManager crashes (it should print a warning instead).

Need to check for these cases in WSM, and possibly in activeParticleTrack too (re-using existing IDs).

**Comment by vtikha** [comment]
I don't think that this should be changed in activeParticleTrack...There is actually no connection from APT to WSM but there is on the other side. Eg. APT does not know of the existence of WSM and therefore has no info on the IDs. And since WSB or somebody else sets " countFrom " it should make sure that no overlapping is happening .

**Comment by gsaponaro** [comment]
That sounds right. I just stress-tested APT by tracking many objects and lowering ```countFrom``` several times between one track and another. No problems there.

Keeping open to remind me to test corner situations with IDs in the WSM<->OPC interaction.

**Comment by vtikha** [comment]
+1
